
name: leadbot_client
description: Flutter client for WhatsApp AI SaaS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  http: ^1.2.1
  shared_preferences: ^2.2.3
  video_player: ^2.9.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  provider: ^6.0.5
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  csv: ^6.0.0
  fluttertoast: ^9.0.0
  connectivity_plus: ^6.1.4
  intl: ^0.19.0
  get: ^4.7.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/lato_thin.ttf
          weight: 100
        - asset: assets/font/lato_regular.ttf
          weight: 400
        - asset: assets/font/lato_medium.ttf
          weight: 500
        - asset: assets/font/lato_semibold.ttf
          weight: 600
        - asset: assets/font/lato_bold.ttf
          weight: 700
