name: humainity_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  lucide_icons: ^0.257.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  flutter_colorpicker: ^1.0.3
  toggle_switch: ^2.3.0
  dotted_border: ^2.1.0 # <-- ADD THIS LINE
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  universal_html: ^2.2.4
  http: ^1.2.1
  provider: ^6.0.5
  image_picker: ^1.0.7
  file_picker: ^8.0.6
  http_parser: ^4.0.2
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.7.1
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  toastification: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/